---
- hosts: localhost
  tasks:

  - name: install packages
    portage:
      package: "{{ item }}"
    with_items:
    - catalyst
    - parted
    - qemu
    - git

  - name: catalyst scripts
    git:
      repo: https://github.com/0xdc/catalyst-scripts
      dest: /release

  - name: fetch upstream stage3
    make:
      chdir: /release/builds/systemd
