---
- hosts: localhost
  tasks:

  - name: install packages
    portage:
      package: "{{ item }}"
    with_items:
    - catalyst
    - parted
    - qemu
    - git

  - name: catalyst storage directory
    file:
      state: directory
      path: "{{ item }}"
    with_items:
    - /release

  - name: fetch upstream stage3
    make:
      chdir: /release/builds/systemd
